version: '2'
services:
    myapp-app:
        image: myapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://myapp-mssql:1433;database=tempdb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myapp-mssql:
        extends:
            file: mssql.yml
            service: myapp-mssql
